### ISSUE TITLE
Build failing in FraudForce SDK in Xcode 11.5 

### ISSUE THREAD

**Issue by prakruth-ct** [iovation/deviceprint-SDK-iOS#12] opened 2020-06-17 13:44 UTC
The Fraud force sdk is failing build in Xcode 11.5 when building using any **Xcode simulator** with following error:
**Building for iOS Simulator, but the linked and embedded framework 'FraudForce.framework' was built for iOS.**
However, if I build using an actual device, it works fine

Could you please look into it at the earliest

**Comment by adamcadaver** [comment] 2020-06-17 18:48
I don't work for iovation but I think if you run `rm -r Frameworks-build/FraudForce.framework` that will fix your issue.

**Comment by mark-sanvitale-iovation** [comment] 2020-06-17 20:28
Correct. You can execute that command manually from a shell whenever alternating between simulator and device. You can also add a script phase as the last step in the build phases of your app target and run that command at the end of every build.

Check Issue #10 for more details. Closing as a duplicate of that issue.

**Closed as completed by mark-sanvitale-iovation** 2020-06-17 20:28 UTC
